chat/urls.py
from django.urls import path
from .views import index, create_chat, chat, leave_chat

app_name = 'chat'

urlpatterns = [
	path('', index, name='index'),
	path('create/', create_chat, name='create_chat'),
	path('<str:chat_id>/', chat, name='chat'),
	path('<str:chat_id>/leave/', leave_chat, name='leave_chat'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from chat import views as chat_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/register', chat_views.register, name='register'),
    path('account/login', auth_views.LoginView.as_view(template_name='chat/login.html'), name='login'),
    path('account/logout', auth_views.LoginView.as_view(template_name='chat/logout.html'), name='logout'),
    path('chat/', include('chat.urls')),
    path('videochat/', chat_views.vide_chat, name="video_chat")
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import random
# Create your models here.

def UniqueGenerator(length=10):
	source = "abcdefghijklmnopqrztuvwxyz"
	result = ""
	for _ in range(length):
		result += source[random.randint(0, length)]

	return result


class GroupCaht(models.Model):
	creator = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=50)
	unique_code = models.CharField(max_length=10, default=UniqueGenerator)
	date_created = models.DateTimeField(default=datetime.now)

class Member(models.Model):
	chat = models.ForeignKey(GroupCaht, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	date_created = models.DateTimeField(default=datetime.now)


	def __str__ (self):
		return self.user.username


class Message(models.Model):
	chat = models.ForeignKey(GroupCaht, on_delete=models.CASCADE)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	text = models.TextField(default="")
	date_created = models.DateTimeField(default=datetime.now)

	

# video chat


status_list = {
    0: 'Contacting',
    1: 'Not available',
    2: 'Accepted',
    3: 'Rejected',
    4: 'Busy',
    5: 'Processing',
    6: 'Ended',
}

class VideoThread(models.Model):
	caller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='caller_user')
	callee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='callee_user')
	status = models.IntegerField(default=0)
	date_started = models.DateTimeField(default=datetime.now)
    date_ended = models.DateTimeField(default=datetime.now)
    date_created = models.DateTimeField(default=datetime.now)

    @property
    def status_name(self):
    	return status_list[self.status]

    @property
    def duration(self):
    	return self.date_ended - self.date_started
    
    

chat/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

chat/views.py
import json
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserRegisterForm
from .models import GroupCaht, Member, VideoThread
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync


# Create your views here.
def register(request):

	if request.method == 'POST':
		form = UserRegisterForm(request.POST)

		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password2')


			user = authenticate(username=username, password=password)

			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('chat:index')
			return redirect('login')
	else:
		form = UserRegisterForm()

	return render(request, "chat/register.html", {"form": form})


@login_required
def index(request):
	current_user = request.user
	return render(request, 'chat/index.html', {'members': current_user.member_set.all()})


@login_required
def create_chat(request):
	current_user = request.user
	title = request.POST['group_name']
	chat = GroupCaht.objects.create(creator_id=current_user.id, title=title)
	Member.objects.create(chat_id=chat.id, user_id=current_user.id)
	return redirect(reverse('chat:chat', args=[chat.unique_code]))

@login_required
def chat(request, chat_id):
	current_user = request.user
	try:
		chat = GroupCaht.objects.get(unique_code=chat_id)
	except GroupCaht.DoesNotExist:
		return render(request, 'chat/404.html')
	if request.method == 'GET':
		if Member.objects.filter(chat_id=chat.id, user_id=current_user.id).count() == 0:
			return render(request, 'chat/join_chat.html', {'chatObject': chat })

		return render(request, 'chat/chat.html', {'chatObject': chat, 'chat_id_json': mark_safe(json.dumps(chat.unique_code))})

	elif request.method == "POST":
		Member.objects.create(chat_id=chat.id, user_id=current_user.id)

		channel_layer = get_channel_layer()
		async_to_sync(channel_layer.group_send)(
			f"chat_{chat.unique_code}",
			{
				'type': 'chat_activity',
				'message': json.dumps({'type': 'join', 'username': current_user.username})
			}
		)

		return render(request, 'chat/chat.html', {'chatObject': chat, 'chat_id_json': mark_safe(json.dumps(chat.unique_code))})

@login_required
def leave_chat(request, chat_id):
	current_user = request.user
	try:
		chat = GroupCaht.objects.get(unique_code=chat_id)
	except GroupCaht.DoesNotExist:
		return render(request, 'chat/404.html')

	if chat.creator_id == current_user.id:
		chat.delete()

		channel_layer = get_channel_layer()

		async_to_sync(channel_layer.group_send)(
			f"chat_{chat.unique_code}",
			{
				'type': 'chat_activity',
				'message': json.dumps({'type': 'delete'})
			}
		)

	else:
		Member.objects.filter(chat_id=chat.id, user_id=current_user.id).delete()


			
		channel_layer = get_channel_layer()
		async_to_sync(channel_layer.group_send)(
			f"chat_{chat.unique_code}",
			{
				'type': 'chat_activity',
				'message': json.dumps({'type': "leave", 'username': current_user.username})
			}
		)

	return redirect('chat:index')	

@login_required
def video_chat(request):
	current_user = request.user
	call_logs = VideoThread.objects.filter(Q(caller_id=current_user.id) | Q(callee_id=current_user.id)).order_by('-date_created')[:5]
	return render(request, 'chat/video_chat.html', {'call_logs': call_logs})

chat/templates/chat/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>Chat Application</title>
    </head>
    <body>
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">Multiple Chat Application</h1>
                <p class="lead">This is an example for creating group chats.</p>
                {% if user.is_authenticated %}
                <h6>You logged in as <strong>{{ user.username }}</strong> - <a href="{% url 'logout' %}" class="">Logout</a></h6>
                {% endif %}
            </div>
        </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- Optional JavaScript -->
        {% block scripts %}{% endblock %}
    </body>
</html>

chat/templates/chat/chat.html
{% extends 'chat/base.html' %}
{% block content %}
<div class="row">
    <div class="mb-sm-3 col-md-7">
        <div class="card">
            <div class="card-header">
                Messages
            </div>
            <div class="card-body">
                <h5 class="card-title">Messages of <strong>{{ chatObject.title }}</strong></h5>
                <div id="messages-list" class="border px-2 py-2 mb-2" style="height: 200px; overflow-y: scroll">
                    {% for message in chatObject.message_set.all %}
                    <div class="media">
                        <div class="media-body">
                            {% if message.author_id == user.id %}
                            <h6 class="my-0 text-success"><strong>You</strong></h6>
                            {% else %}
                            <h6 class="my-0"><strong>{{ message.author }}</strong></h6>
                            {% endif %}
                            <p>{{ message.text }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="form-inline">
                    <div class="form-group mr-2 mb-2">
                    <input type="text" class="form-control" id="msg-input" placeholder="Enter your Message Text">
                    </div>
                    <button id="msg-submit" type="submit" class="btn btn-primary mb-2">Send</button>   
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="card">
            <div class="card-header">
                Members
            </div>
            <div class="card-body">
                <div id="members-list" class="list-group">
                    <p class="card-text">Shere this chat link with your friends: <a href="{{ request.scheme }}://{{ request.get_host }}{% url 'chat:chat' chatObject.unique_code %}">{{ request.scheme }}://{{ request.get_host }}{% url 'chat:chat' chatObject.unique_code %}</a></p>
                    {% for member in chatObject.member_set.all %}
                    <li id="item-{{ member }}" href="#" class="list-group-item">{{ member }}</li>
                    {% endfor %}
                </div>
                <a href="{% url 'chat:leave_chat' chatObject.unique_code %}" class="btn btn-danger mt-3">Leave Conversation</a>
                {% if chatObject.creator_id == user.id %}
                <p class="text-muted mt-2">If you leave this chat it will be deleted.</p>  
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
<script>
    var chat_id = {{ chat_id_json }};
    var msgdiv = $('#messages-list');
    var memberdiv = $('#members-list');

    window.onload = function(e){
        msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
    }

    var socket = new WebSocket(
    'ws://' + window.location.host +
    '/ws/chat/' + chat_id + '/');

    socket.onmessage = function(e) {
        var message = JSON.parse(e.data);
        switch (message['type']) {
            case "join":
                memberdiv.append(`
                    <li id="item-USERNAME" href="#" class="list-group-item">USERNAME</li>
                `.replace('USERNAME', message['username']).replace('USERNAME', message['username']));

                msgdiv.append(`
                    <div class="mx-auto" style="width: max-content;">
                        USERNAME joined the chat
                    </div>
                `.replace('USERNAME', message['username']));
                break;
            case "leave":
                $('#item-'+ message['username']).remove();

                msgdiv.append(`
                    <div class="mx-auto" style="width: max-content;">
                        USERNAME left the chat
                    </div>
                `.replace('USERNAME', message['username']));
                break;
            case "delete":
                alert('Chat was deleted by its creator.');
                window.location.href = window.location.origin + '/chat/';
                break;
            case "msg":
                msgdiv.append(`
                    <div class="media">
                        <div class="media-body">
                            <h6 class="my-0"><strong>USERNAME</strong></h6>
                            <p>MESSAGE</p>
                        </div>
                    </div>
                `.replace('USERNAME', message['sender']).replace('MESSAGE', message['text']));
                break;
            default:
                break;
        }
        msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
    };

    socket.onclose = function(e) {
        console.error('Socket closed unexpectedly');
    };

    document.querySelector('#msg-input').focus();
    document.querySelector('#msg-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#msg-submit').click();
        }
    };

    document.querySelector('#msg-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#msg-input');
        var message = messageInputDom.value;

        msgdiv.append(`
            <div class="media">
                <div class="media-body">
                    <h6 class="my-0 text-success"><strong>You</strong></h6>
                    <p>MESSAGE</p>
                </div>
            </div>
        `.replace('MESSAGE', message));

        msgdiv.scrollTop(msgdiv.prop("scrollHeight"));

        socket.send(JSON.stringify({'text': message}));

        messageInputDom.value = '';
    };
</script>
{% endblock scripts %}

chat/templates/chat/index.html
{% extends "chat/base.html" %}
{% block content %}
    <div class="row">
        <div class="mb-sm-3 col-md-6">
            <div class="card">
                <div class="card-header">
                    Create Multiple Chats
                </div>
                <div class="card-body">
                    <h5 class="card-title">Create Chat</h5>
                    <p class="card-text">You can create your own group chat here.</p>
                    <form action="{% url 'chat:create_chat' %}" method="POST" class="form-inline">
                        {% csrf_token %}
                        <div class="form-group mr-2 mb-2">
                            <label for="id_group_name" class="sr-only">Group Name</label>
                            <input type="text" class="form-control" name="group_name" id="id_group_name" placeholder="Group Name">
                        </div>
                        <button type="submit" class="btn btn-primary mb-2">Create</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    My Chats
                </div>
                <div class="card-body">
                    <div class="list-group">
                        <p class="card-text">You can see a list of chats you've joined/created.</p>
                        {% for member in members %}
                        <a href="{% url 'chat:chat' member.chat.unique_code %}" class="list-group-item list-group-item-action">{{ member.chat.title }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

chat/templates/chat/join_chat.html
{% extends 'chat/base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header">
            Join to chat
        </div>
        <div class="card-body">
            <h5 class="card-title">Join to <strong>{{ chatObject.title }}</strong></h5>
            <p class="card-text">Would you like to join this chat?</p>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-success mb-2">Join</button> 
            </form>
        </div>
    </div>
</div>
{% endblock content %}

chat/templates/chat/login.html
{% extends 'chat/base.html' %}
{% block content %}
<div class="card mb-5">
    <div class="card-header">
        Login
    </div>
    <div class="card-body">
        <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username</label>
                <input type="text" class="form-control" name="username" required id="id_username" placeholder="Username">
            </div>
            <div class="form-group">
                <label for="id_password">Password</label>
                <input type="password" class="form-control" name="password" required id="id_password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <div class="border-top pt-2 mt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
</div>

{% endblock content %}

chat/templates/chat/logout.html
{% extends 'chat/base.html' %}
{% block content %}
<h4>You have been logged out.</h4>
<a href="{% url 'login' %}" class="btn btn-outline-primary mt-2">Login again</a>
{% endblock content %}

chat/templates/chat/register.html
{% extends 'chat/base.html' %}
{% block content %}
<div class="card mb-5">
    <div class="card-header">
        Login
    </div>
    <div class="card-body">
        <form action="{% url 'register' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username</label>
                <input type="text" class="form-control" name="username" required id="id_username" aria-describedby="usernameHelp" placeholder="Enter Username">
                <small id="usernameHelp" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
            </div>
            <div class="form-group">
                <label for="id_email">Email address</label>
                <input type="email" class="form-control" name="email" required id="id_email" placeholder="Enter Email">
            </div>
            <div class="form-group">
                <label for="id_password1">Password</label>
                <input type="password" class="form-control" name="password1" required id="id_password1" aria-describedby="passwordHelp" placeholder="Password">
                <small id="passwordHelp" class="form-text text-muted">Your password can't be too similar to your other personal information.</small>
                <small id="passwordHelp" class="form-text text-muted">Your password must contain at least 8 characters.</small>
                <small id="passwordHelp" class="form-text text-muted">Your password can't be a commonly used password.</small>
                <small id="passwordHelp" class="form-text text-muted">Your password can't be entirely numeric.</small>
            </div>
            <div class="form-group">
                <label for="id_password2">Password Confirmation</label>
                <input type="password" class="form-control" name="password2" required id="id_password2" placeholder="Confirm Password">
            </div> 
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <div class="border-top pt-2 mt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
</div>

{% endblock content %}

chat/templates/chat/video_chat_base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

        <title>Chat Application</title>
    </head>
    <body>
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">Video Chat Application</h1>
                <p class="lead">This is an example for creating peer to peer video chats.</p>
                {% if user.is_authenticated %}
                <h6>You logged in as <strong>{{ user.username }}</strong> - <a href="{% url 'logout' %}" class="">Logout</a></h6>
                {% endif %}
            </div>
        </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- Optional JavaScript -->
        {% block scripts %}{% endblock %}
    </body>
</html>